# ===============================
# Application
# ===============================
spring.application.name=notification-system
server.port=8080


# ===============================
# Database (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5438/notification_db
spring.datasource.username=postgres
spring.datasource.password=Abhi@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# Mail Configuration (Gmail SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abhisheklad963@gmail.com
spring.mail.password=icqpiuqwaeakkrny

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ===============================
# Kafka Configuration
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Auto topic creation (optional)
spring.kafka.admin.auto-create=true